name: MineCord
description: Easily links Discord to Minecraft
version: 0
main: MineCord.Plugin.Main

commands:
  announce:
    description: Announce to the dedicated Discord channel
    permission: op
  get:
    description: Get details of a player
    permission: op
  seeinv:
    description: View, not edit, a player's inventory
    permission: op